sourceSystem : "JDE_UK"
systemIdentifier : "UK1"
default_expiryDate: "2999-09-09"

itemType: "CONCRETE_MIX"
unitOfMeasurement: "CUBIC_METER"

#for testing
https.port: "8058"

#country codes
United Kingdom: "GB"
Great Britain: "GB"
Andorra: "AD"
United Arab Emirates (UAE): "AE"
Afghanistan: "AF"
Antigua and Barbuda: "AG"
Anguilla: "AI"
Albania: "AL"
Armenia: "AM"
Netherlands Antilles: "AN"
Angola: "AO"
Antarctica: "AQ"
Argentina: "AR"
American Samoa: "AS"
Austria: "AT"
Australia: "AU"
Aruba: "AW"
Azerbaijan: "AZ"
Bosnia and Herzegovina: "BA"
Barbados: "BB"
Bangladesh: "BD"
Belgium: "BE"
Burkina Faso: "BF"
Bulgaria: "BG"
Bahrain: "BH"
Burundi: "BI"
Benin: "BJ"
Bermuda: "BM"
Brunei: "BN"
Bolivia: "BO"
Brazil: "BR"
Bahamas: "BS"
Bhutan: "BT"
Burma/Myanmar: "BU"
Bouvet Island: "BV"
Botswana: "BW"
Byelorussian SSR: "BY"
Belize: "BZ"
Canada: "CA"
Cocos (Keeling) Islands: "CC"
Democratic Republic of Congo: "CD"
Central African Republic: "CF"
Congo: "CG"
Switzerland: "CH"
Channel Islands: "CI"
Cook Islands: "CK"
Chile: "CL"
Cameroon: "CM"
China: "CN"
Colombia: "CO"
Costa Rica: "CR"
Serbia and Montenegro: "CS"
Cuba: "CU"
Cape Verde: "CV"
Christmas Island: "CX"
Cyprus: "CY"
Czech Rebulic: "CZ"
Germany: "DE"
Djibouti: "DJ"
Denmark: "DK"
Dominica: "DM"
Dominican Republic: "DO"
#Democratic Republic of Congo: "DR"C
Algeria: "DZ"
Estonia: "EA"
Ecuador: "EC"
#Estonia: "EE"
Egypt: "EG"
Western Sahara: "EH"
Eritrea: "ER"
Spain: "ES"
Ethiopia: "ET"
Finland: "FI"
Fiji: "FJ"
Falkland Islands: "FK"
Micronesia: "FM"
Faroe Islands: "FO"
France: "FR"
Gabon: "GA"
#Gabon: "GA"B
#United Kingdom: "GB"
Grenada: "GD"
Georgia: "GE"
French Guiana: "GF"
Ghana: "GH"
Gibraltar: "GI"
Greenland: "GL"
Gambia: "GM"
Guinea: "GN"
Guadeloupe: "GP"
Equatorial Guinea: "GQ"
Greece: "GR"
Guernsey: "GS"
Guatemala: "GT"
Guam: "GU"
Guinea-Bissau: "GW"
Guyana: "GY"
Hong Kong: "HK"
Heard Island and McDonald Isla: "HM"
Honduras: "HN"
Croatia: "HR"
Haiti: "HT"
Hungary: "HU"
Indonesia: "ID"
Ireland: "IE"
Israel: "IL"
India: "IN"
British Indian Ocean Territory: "IO"
Iraq: "IQ"
Iran: "IR"
Iceland: "IS"
Italy: "IT"
Jersey: "JE"
Jamaica: "JM"
Jordan: "JO"
Japan: "JP"
Kenya: "KE"
Kyrgyzstan: "KG"
Cambodia: "KH"
Kiribati: "KI"
Comoros: "KM"
Saint Kitts and Nevis: "KN"
North Korea: "KP"
South Korea: "KR"
Kuwait: "KW"
Cayman Islands: "KY"
Kazakhstan: "KZ"
Laos: "LA"
#Latvia: "LA"T
Lebanon: "LB"
Saint Lucia: "LC"
Liechtenstein: "LI"
#Lithuania: "LI"T
Sri Lanka: "LK"
Liberia: "LR"
Lesotho: "LS"
Lithuania: "LT"
Luxembourg: "LU"
Latvia: "LV"
Libya: "LY"
Morocco: "MA"
Monaco: "MC"
Moldova, Republic of: "MD"
Madagascar: "MG"
Marshall Islands: "MH"
Macedonia, The Former Yugoslav: "MK"
Mali: "ML"
Myanmar: "MM"
Mongolia: "MN"
Macao: "MO"
Northern Mariana Islands: "MP"
Martinique: "MQ"
Mauritania: "MR"
Montserrat: "MS"
Malta: "MT"
Mauritius: "MU"
Maldives: "MV"
Malawi: "MW"
Mexico: "MX"
Malaysia: "MY"
Mozambique: "MZ"
Namibia: "NA"
New Caledonia: "NC"
Niger: "NE"
Norfolk Island: "NF"
Nigeria: "NG"
Nicaragua: "NI"
Netherlands: "NL"
None: "NN"
Norway: "NO"
Nepal: "NP"
Nauru: "NR"
Niue: "NU"
New Zealand: "NZ"
Oman: "OM"
Panama: "PA"
Peru: "PE"
French Polynesia: "PF"
Papua New Guinea: "PG"
Phillippines: "PH"
Pakistan: "PK"
Poland: "PL"
St. Pierre and Miquelon: "PM"
Pitcairn: "PN"
Puerto Rico: "PR"
Palestinian Territory, Occupie: "PS"
Portugal: "PT"
Palau: "PW"
Paraguay: "PY"
Qatar: "QA"
Reunion: "RE"
Romania: "RO"
Russia: "RU"
Rwanda: "RW"
Saudi Arabia: "SA"
Solomon Islands: "SB"
Seychelles: "SC"
Sudan: "SD"
Sweden: "SE"
Singapore: "SG"
Saint Helena: "SH"
Slovenia: "SI"
Svalbard and Jan Mayen: "SJ"
Slovakia: "SK"
Sierra Leone: "SL"
San Marino: "SM"
Senegal: "SN"
Somalia: "SO"
Suriname: "SR"
Sao Tome and Principe: "ST"
USSR: "SU"
El Salvador: "SV"
Syria: "SY"
Swaziland: "SZ"
Turks and Caicos Islands: "TC"
Chad: "TD"
French Southern Territory: "TF"
Togo: "TG"
Thailand: "TH"
Tajikistan: "TJ"
Tokelau: "TK"
Timor-Leste: "TL"
Turkmenistan: "TM"
Tunisia: "TN"
Tonga: "TO"
Turkey: "TR"
Trinidad and Tobago: "TT"
Tuvalu: "TV"
Taiwan: "TW"
Tanzania: "TZ"
Ukrainian SSR: "UA"
Uganda: "UG"
United States Minor Outlying I: "UM"
United States: "US"
Uruguay: "UY"
Uzbekistan: "UZ"
Vatican City: "VA"
Saint Vincent & the Grenadines: "VC"
Venezuela: "VE"
British Virgin Islands: "VG"
US Virgin Islands: "VI"
Vietnam: "VN"
Vanuatu: "VU"
Wallis and Futuna Islands: "WF"
Samoa: "WS"
Yemen: "YE"
Mayotte: "YT"
Yugoslavia: "YU"
South Africa: "ZA"
Zambia: "ZM"
Zimbabwe: "ZW"
